apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "openjdk-qe-default-limits"
spec:
  limits:
    - type: Container
      default:
        cpu: "2"
        memory: 512Mi
      defaultRequest:
        cpu: "1"
        memory: 256Mi